ls:
  .dir: kebab-case
  .md: kebab-case | regex:[0-9A-Z\-]+

ignore:
  - .git
  - node_modules
  - .github
  - .vscode
  - .idea
  - .cspell.json
  -  workflow-group-4.github.io/node_modules/.cache
  -  workflow-group-4.github.io/node_modules/
  -  workflow-group-4.github.io