ls:
  .dir: kebab-case
  .md: kebab-case | regex:[0-9A-Z\-]+

ignore:
  - .git
  - node_modules
  - .github
  - .vscode
  - workflow-group-4.github.io
  - workflow-group-4.github.io/node_modules
  - workflow-group-4.github.io/node_modules/.cache
  - workflow-group-4.github.io/students-bio/workflow-group-4.github.io
  - .idea
  - .idea/codeStyles
